### PR TITLE
Links to some r10k articles I wrote.

### PR DESCRIPTION
**Pull request by rnelson0**

### CODE REVIEW

**Comment by igalic** [comment]
tbh, i'd rather have their contents under a drafts/ folder.

**Comment by igalic** [comment]
maybe i should add a contributing.md ;)

**Comment by rnelson0** [comment]
Moved into drafts/r10k.md

**Comment by rnelson0** [comment]
@igalic the blog series articles have a continuity that may be lost by taking the posts themselves. If you're looking for the core of the patterns, I could probably write up a separate article that doesn't rely on the umpteen other posts for this. Would that help?

**Comment by igalic** [comment]
i'll read through them and see what we can extract.

**Comment by rnelson0** [comment]
@igalic Are you planning to keep this alive? Perhaps we can work on it at the community hackathon.

**Comment by igalic** [comment]
YES. thank you for the reminder

**Pull request merged**
